### ISSUE TITLE
Does VcsBackendAnnotation support vcs Q-2020.03-SP2?

### ISSUE THREAD

**Issue by Wolf-Tungsten** [ucb-bar/chiseltest#520]
Hi! I am using vcs as simulator backend these days. For the same test, vcs O-2018.09-SP2 works well but Q-2020.03-SP2 failed.
I get the following error output which seems to indicate that my vcs did not compile successfully.
```
Compiling /************/build.sc
[68/68] *******.test.testOnly
MatchMergeTest:
- ********Test *** FAILED ***
  os.SubprocessException: CommandResult 2

2 modules and 0 UDP read.
g++ -w  -pipe -fPIC "-ICS_HOME/include -I/*******/test_run_dir/******Test -fPIC -std=c++11" -O -I/tools/Synopsys/vcs/Q-2020.03-SP2/include    -c ../vpi.cpp
In file included from ../vpi.cpp:1:0:
../vpi.h: In member function 'void vpi_api_t::init_ins()':
../vpi.h:35:20: error: 'nullptr' was not declared in this scope
     if(arg_iter != nullptr) {
                    ^
../vpi.h: In member function 'void vpi_api_t::init_outs()':
../vpi.h:46:20: error: 'nullptr' was not declared in this scope
     if(arg_iter != nullptr) {
                    ^
make[1]: *** [vpi.o] Error 1
make: *** [product_clean_order] Error 2
Make exited with status 2
Verdi KDB elaboration done and the database successfully generated: 0 error(s), 0 warning(s)
  at os.proc.call(ProcessOps.scala:85)
  at chiseltest.simulator.VcsSimulator$.compileSimulation(VcsSimulator.scala:128)
  at chiseltest.simulator.VcsSimulator$.createContext(VcsSimulator.scala:95)
  at chiseltest.internal.BackendExecutive$.start(BackendExecutive.scala:36)
  at chiseltest.defaults.package$.createDefaultTester(defaults.scala:21)
  at chiseltest.ChiselScalatestTester$TestBuilder.apply(ChiselScalatestTester.scala:31)
  at *******.$anonfun$new$1(*******.scala:145)
  at ***********Test$$Lambda$121/1292838001.apply(Unknown Source)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
  ...
1 targets failed
*********.test.testOnly 1 tests failed:
  ******** *******Test
```

I write this test with `.withAnnotations(Seq(VcsBackendAnnotation, WriteFsdbAnnotation)) `. 
It seems that the new version of vcs doesn't handle a certain flag correctly?

**Comment by Wolf-Tungsten** [comment]
Well, now I can confirm that chiseltest supports vcs Q-2020.03-SP2.

The above problem is caused by my configuration not allowing vcs to find new versions of g++.
