### ISSUE TITLE
Report assert message with `FailedBoundedCheckException`

### ISSUE THREAD

**Issue by yupferris** [ucb-bar/chiseltest#652]
When using BMC with more than one `assert` in a design, the model checker can correctly identify violations, but it's difficult to identify which assertion failed. Example output:

```
[info] - should pass formal checks *** FAILED ***
[info]   chiseltest.formal.FailedBoundedCheckException: [<omitted>] found an assertion violation 0 steps after reset!
[info]   at chiseltest.formal.FailedBoundedCheckException$.apply(Formal.scala:26)
[info]   at chiseltest.formal.backends.Maltese$.bmc(Maltese.scala:84)
[info]   at chiseltest.formal.Formal$.executeOp(Formal.scala:82)
[info]   at chiseltest.formal.Formal$.$anonfun$verify$2(Formal.scala:62)
[info]   at chiseltest.formal.Formal$.$anonfun$verify$2$adapted(Formal.scala:62)
[info]   at scala.collection.immutable.List.foreach(List.scala:333)
[info]   at chiseltest.formal.Formal$.verify(Formal.scala:62)
[info]   at chiseltest.formal.Formal.verify(Formal.scala:34)
[info]   at chiseltest.formal.Formal.verify$(Formal.scala:32)
[info]   at tse.SliceLoadStoreUnitTests.verify(<omitted>.scala:17)
[info]   ...
```

We [previously discussed](https://github.com/ucb-bar/chiseltest/issues/647) ways of working around this (particularly, making specific test bench wrappers around the DUT and specifying formal properties on _those_ instead of the DUT itself), but I've since noticed that `assert` can also accept a message string. It would be excellent if that string could be presented as part of the error message.

**Comment by Gallagator** [comment]
Maybe this is a tad late for you but, looking at this, functionality seems to be mostly written, it's just not accessible by the user. [See here](https://github.com/ucb-bar/chiseltest/blob/main/src/main/scala/chiseltest/formal/backends/smt/SMTModelChecker.scala#L135-L154).

It seems all `SMTModelCheckers` are created with `performance` settings  [see here](https://github.com/ucb-bar/chiseltest/blob/main/src/main/scala/chiseltest/formal/backends/smt/SMTModelChecker.scala#L135-L154) but it should be trivial to pass a parameter through to Maltese and instantiate the model checkers so they check each assertion one at a time. ([This is where they are created](https://github.com/ucb-bar/chiseltest/blob/main/src/main/scala/chiseltest/formal/backends/Maltese.scala#L210-L215)). Note that `.btor` based engines would be difficult to support so you might want to pass this option through one of the engine annotations.
