### ISSUE TITLE
chiseltest gets the signal name wrong when trying to peek, poke, or expect an OpaqueType

### ISSUE THREAD

**Issue by konda-x1** [ucb-bar/chiseltest#661]
When a `Record` extends `OpaqueType`, it can only have one element with an empty string as its name (provided that its `opaqueType` method returns `true`). In that case, during elaboration, chisel doesn't append any underscores to a signal with the `Record` type. However, chiseltest still tries to append an underscore, thus getting the wrong signal name.

Example:
```scala
import chisel3.experimental.BundleLiterals.AddBundleLiteralConstructor
import chisel3.experimental.OpaqueType
import chisel3.{fromDoubleToLiteral => _, fromIntToBinaryPoint => _, _}
import chiseltest._
import org.scalatest.flatspec.AnyFlatSpec

import scala.collection.immutable.SeqMap

class OpaqueTypeSpec extends AnyFlatSpec with ChiselScalatestTester {

  class OpaqueRecord[T <: Data](val data: T) extends Record with OpaqueType {
    val elements: SeqMap[String, T] = SeqMap("" -> data)
  }

  //noinspection TypeAnnotation
  class OpaquePassthrough[T <: Data](data: T) extends Module {
    val in = IO(Input(new OpaqueRecord(data)))
    val out = IO(Output(new OpaqueRecord(data)))
    out := in
  }

  behavior of "OpaqueType"

  it should "poke and expect successfully" in {
    test(new OpaquePassthrough(SInt(8.W))) { dut =>
      def sIntVal = -4.S(8.W)
      def sIntRec = new OpaqueRecord(SInt(8.W)).Lit(_.data -> sIntVal)
      dut.in.poke(sIntRec)
      dut.out.expect(sIntRec)
    }
  }

}

```

yields the following error message:

```
[info] OpaqueTypeSpec:
[info] OpaqueType
[info] - should poke and expect successfully *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: Error: getValue("in_") : argument is not an element of this circuit
[info]   at scala.Predef$.assert(Predef.scala:279)
[info]   at treadle.executable.ExecutionEngine.getValue(ExecutionEngine.scala:238)
[info]   at treadle.TreadleTester.peek(TreadleTester.scala:303)
[info]   at chiseltest.simulator.TreadleContext.peek(TreadleSimulator.scala:85)
[info]   at chiseltest.internal.GenericBackend.pokeBits(GenericBackend.scala:70)
[info]   at chiseltest.package$Utils$.pokeBits(package.scala:461)
[info]   at chiseltest.package$testableSInt.poke(package.scala:85)
[info]   at chiseltest.package$testableSInt.poke(package.scala:81)
[info]   at chiseltest.package$testableData.pokeInternal(package.scala:291)
[info]   at chiseltest.package$testableData.$anonfun$pokeInternal$2(package.scala:297)
[info]   at chiseltest.package$testableData.$anonfun$pokeInternal$2$adapted(package.scala:296)
[info]   at scala.collection.immutable.List.foreach(List.scala:333)
[info]   at chiseltest.package$testableData.pokeInternal(package.scala:296)
[info]   at chiseltest.package$testableData.poke(package.scala:263)
[info]   at OpaqueTypeSpec.$anonfun$new$4(OpaqueTypeSpec.scala:28)
[info]   at OpaqueTypeSpec.$anonfun$new$4$adapted(OpaqueTypeSpec.scala:25)
[info]   at chiseltest.internal.GenericBackend.$anonfun$run$1(GenericBackend.scala:170)
[info]   at chiseltest.internal.ThreadedBackend$TesterThread$$anon$1.$anonfun$run$1(ThreadedBackend.scala:495)
[info]   at chiseltest.internal.GenericBackend.doTimescope(GenericBackend.scala:104)
[info]   at chiseltest.internal.ThreadedBackend$TesterThread$$anon$1.run(ThreadedBackend.scala:495)
[info]   at java.base/java.lang.Thread.run(Thread.java:1623)
```

The problem is that `BackendExecutive.getDataNames` doesn't account for `Record`s that extend `OpaqueType`. However, what I've noticed is that this function (or rather, the one expression using this function in BackendExecutive.scala) is essentially trying to return the same result as `chisel3.reflect.DataMirror.fullModulePorts`. I think that replacing `getDataNames` with `fullModulePorts` in the one place it's being used will solve this issue. In `BackendExecutive.start`, replace:

```scala
val portNames = DataMirror.modulePorts(dut).flatMap { case (name, data) => getDataNames(name, data).toList }.toMap
```

with:

```scala
val portNames = DataMirror.fullModulePorts(dut).map(_.swap).toMap
```

...and that should solve the issue.

**Comment by ekiwi** [comment]
Thanks! Do you want to make a PR with your new test and the fix?

**Comment by ekiwi** [comment]
How about you make a PR against the `main` branch and I will see about backporting it to `0.6.x`?
